# Generated by Django 5.1 on 2026-08-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='content_format',
            field=models.CharField(choices=[('MARKDOWN', 'Markdown'), ('HTML', 'HTML')], default='MARKDOWN', max_length=10),
        ),
    ]
