# Generated by Django 5.1 on 2026-07-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_lesson_content_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='content_data',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content_type',
            field=models.CharField(choices=[('VIDEO', 'Video'), ('PDF', 'PDF'), ('DOCUMENT', 'Document'), ('IMAGE', 'Image'), ('TEXT', 'Text')], max_length=20),
        ),
    ]
