# Generated by Django 5.1 on 2026-07-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_lesson_content_data_alter_lesson_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='content_data',
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content_type',
            field=models.CharField(choices=[('VIDEO', 'Video'), ('PDF', 'PDF'), ('DOCUMENT', 'Document'), ('IMAGE', 'Image'), ('TEXT', 'Text')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
