# Generated by Django 5.1 on 2026-09-07 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0004_consolidate_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('caption', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='class_feed/attachments/%Y/%m/')),
                ('attachment_original_name', models.CharField(blank=True, max_length=255)),
                ('attachment_type', models.CharField(blank=True, choices=[('IMAGE', 'Image'), ('VIDEO', 'Video')], max_length=20)),
                ('attachment_size', models.PositiveIntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_posts', to='courses.course')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='feed_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['course', '-created_at'], name='class_feed__course__22fbdb_idx')],
            },
        ),
    ]
