# Generated by Django 5.1 on 2026-09-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='grading_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='short_answer_grading_mode',
            field=models.CharField(choices=[('MANUAL', 'Manual Review'), ('AI', 'AI Grading')], default='MANUAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='grading_status',
            field=models.CharField(choices=[('AUTO_GRADED', 'Auto Graded'), ('PENDING_GRADING', 'Pending Grading'), ('MANUALLY_GRADED', 'Manually Graded'), ('AI_GRADED', 'AI Graded')], default='AUTO_GRADED', max_length=20),
        ),
    ]
