# Generated by Django 5.1 on 2026-07-30 17:55

import django.core.validators
from django.db import migrations, models


def backfill_short_answer_grading_status(apps, schema_editor):
    QuizAnswer = apps.get_model("quizzes", "QuizAnswer")
    QuizAnswer.objects.filter(question__question_type="SHORT_ANSWER").update(
        grading_status="PENDING_GRADING", marks_awarded=None
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_category_description'),
        ('modules', '0001_initial'),
        ('quizzes', '0002_quiz_module'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['module', 'order']},
        ),
        migrations.AddField(
            model_name='question',
            name='marks',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='quiz',
            name='attempts_allowed',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='quiz',
            name='available_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='available_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='grading_status',
            field=models.CharField(choices=[('AUTO_GRADED', 'Auto Graded'), ('PENDING_GRADING', 'Pending Grading'), ('MANUALLY_GRADED', 'Manually Graded')], default='AUTO_GRADED', max_length=20),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='marks_awarded',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('GRADED', 'Graded'), ('EXPIRED', 'Expired')], default='IN_PROGRESS', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='quiz',
            constraint=models.UniqueConstraint(condition=models.Q(('module__isnull', False)), fields=('module', 'order'), name='unique_quiz_order_per_module'),
        ),
        migrations.RunPython(backfill_short_answer_grading_status, noop_reverse),
    ]
