# Generated by Django 5.1 on 2026-08-02 13:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_alter_quiz_options_question_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='last_activity_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('GRADED', 'Graded'), ('EXPIRED', 'Expired'), ('ABANDONED', 'Abandoned')], default='IN_PROGRESS', max_length=20),
        ),
    ]
