# Generated by Django 5.1 on 2026-08-19 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0003_pathway_order_pathway_tier_and_more'),
        ('tiers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TierPathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_pathways', to='pathways.pathway')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_pathways', to='tiers.tier')),
            ],
            options={
                'ordering': ['tier', 'order'],
                'constraints': [models.UniqueConstraint(fields=('tier', 'order'), name='unique_tierpathway_order_per_tier')],
                'unique_together': {('tier', 'pathway')},
            },
        ),
    ]
