# Generated by Django 5.1 on 2026-08-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0003_backfill_tierpathway'),
    ]

    operations = [
        migrations.AddField(
            model_name='tier',
            name='category',
            field=models.CharField(choices=[('ATHLETIC', 'Athletic'), ('ACADEMIC', 'Academic'), ('PROFESSIONAL', 'Professional'), ('VOCATIONAL', 'Vocational'), ('FOUNDATION', 'Foundation'), ('LEGACY', 'Legacy')], default='ACADEMIC', max_length=20),
        ),
        migrations.AddField(
            model_name='tier',
            name='estimated_duration',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
