# Generated by Django 5.1 on 2026-08-19 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0005_backfill_unlocks_from_pathway_purchases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tier',
            name='unlock_threshold_percent',
        ),
    ]
