# Generated by Django 5.1 on 2026-08-20 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0010_finalize_tier_category_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tier',
            name='thumbnail',
        ),
    ]
