# Generated by Django 5.1 on 2026-09-03 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_drill', '0003_admindrillquizquestion_admindrillquizchoice_and_more'),
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointstransaction',
            name='admin_drill_progress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_transactions', to='daily_drill.admindrillprogress'),
        ),
        migrations.AddField(
            model_name='pointstransaction',
            name='ai_drill_generation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_transactions', to='daily_drill.aidrillgeneration'),
        ),
    ]
