# Generated by Django 5.1 on 2026-09-03 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_pointstransaction_admin_drill_progress_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='fulfillment_type',
            field=models.CharField(choices=[('SCHEDULED_SESSION', 'Scheduled Session'), ('EVENT_ACCESS', 'Event Access'), ('DIGITAL_CODE', 'Digital Code'), ('DIGITAL_ACCESS', 'Digital Access'), ('PHYSICAL_DELIVERY', 'Physical Delivery'), ('PROFILE_BADGE', 'Profile Badge'), ('MANUAL_FULFILLMENT', 'Manual Fulfillment')], default='MANUAL_FULFILLMENT', max_length=20),
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_redemptions_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_redemptions_cancelled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='student_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rewardredemption',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('SCHEDULED', 'Scheduled'), ('READY', 'Ready'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='RewardFulfillment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('meeting_method', models.CharField(blank=True, choices=[('ZOOM', 'Zoom'), ('GOOGLE_MEET', 'Google Meet'), ('TEAMS', 'Microsoft Teams'), ('IN_PERSON', 'In Person')], max_length=20)),
                ('meeting_url', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_fulfillments_completed', to=settings.AUTH_USER_MODEL)),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_reward_sessions', to=settings.AUTH_USER_MODEL)),
                ('redemption', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment', to='rewards.rewardredemption')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
