# Generated by Django 5.1 on 2026-09-04 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_assignment_ai_review_reward_points_and_more'),
        ('daily_drill', '0003_admindrillquizquestion_admindrillquizchoice_and_more'),
        ('rewards', '0003_reward_duration_minutes_reward_fulfillment_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pointstransaction',
            name='assignment_ai_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_transactions', to='assignments.assignmentaireview'),
        ),
        migrations.AlterField(
            model_name='pointstransaction',
            name='transaction_type',
            field=models.CharField(choices=[('DRILL_REWARD', 'Daily Drill Reward'), ('REDEMPTION', 'Reward Redemption'), ('REDEMPTION_REFUND', 'Redemption Refund'), ('MANUAL_ADJUSTMENT', 'Manual Adjustment'), ('ASSIGNMENT_AI_REVIEW', 'AI-Graded Assignment Reward')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='pointstransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('assignment_ai_review__isnull', False)), fields=('assignment_ai_review',), name='one_points_transaction_per_ai_review'),
        ),
    ]
