# Generated by Django 5.1 on 2026-09-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0004_pointstransaction_assignment_ai_review_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pointstransaction',
            name='one_points_transaction_per_ai_review',
        ),
        migrations.RemoveField(
            model_name='pointstransaction',
            name='assignment_ai_review',
        ),
        migrations.AlterField(
            model_name='pointstransaction',
            name='transaction_type',
            field=models.CharField(choices=[('DRILL_REWARD', 'Daily Drill Reward'), ('REDEMPTION', 'Reward Redemption'), ('REDEMPTION_REFUND', 'Redemption Refund'), ('MANUAL_ADJUSTMENT', 'Manual Adjustment')], max_length=20),
        ),
    ]
