# Generated by Django 5.1 on 2026-07-27 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_tag_course_difficulty_course_duration_minutes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
