# Generated by Django 5.1 on 2026-08-03 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_category_description'),
        ('courses', '0004_course_code'),
    ]

    operations = [
    ]
