# Generated by Django 5.1 on 2026-10-01 09:43

import django.core.validators
from django.db import migrations, models

from courses.grades import parse_grade_range


def backfill_grade_ranges(apps, schema_editor):
    Course = apps.get_model("courses", "Course")
    for course in Course.objects.only("id", "description").iterator():
        grades = parse_grade_range(course.description)
        if grades:
            Course.objects.filter(pk=course.pk).update(
                grade_min=grades[0], grade_max=grades[1]
            )


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_consolidate_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='grade_max',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='course',
            name='grade_min',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.RunPython(backfill_grade_ranges, migrations.RunPython.noop),
    ]
