# Generated by Django 5.1 on 2026-10-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_audience_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='learning_outcomes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
