# Generated by Django 5.1 on 2026-08-14 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('onboarding', '0001_initial'),
        ('pathways', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionoptionpathwayweight',
            name='pathway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_weights', to='pathways.pathway'),
        ),
        migrations.AlterUniqueTogether(
            name='questionnaireanswer',
            unique_together={('user', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='questionoptionpathwayweight',
            unique_together={('option', 'pathway')},
        ),
    ]
