# Generated by Django 5.1 on 2026-08-18 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('onboarding', '0001_initial'),
        ('pathways', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingprogress',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionnaireanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='onboarding.question'),
        ),
        migrations.AddField(
            model_name='questionnaireanswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='onboarding.question'),
        ),
        migrations.AddField(
            model_name='questionnaireanswer',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='onboarding.questionoption'),
        ),
        migrations.AddField(
            model_name='questionoptionpathwayweight',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathway_weights', to='onboarding.questionoption'),
        ),
        migrations.AddField(
            model_name='questionoptionpathwayweight',
            name='pathway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_weights', to='pathways.pathway'),
        ),
        migrations.AlterUniqueTogether(
            name='questionnaireanswer',
            unique_together={('user', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='questionoptionpathwayweight',
            unique_together={('option', 'pathway')},
        ),
    ]
