# Generated by Django 5.1 on 2026-07-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='grading_mode',
            field=models.CharField(choices=[('MANUAL', 'Manual Review'), ('AUTO', 'Auto-Check on Submit')], default='MANUAL', max_length=20),
        ),
    ]
