# Generated by Django 5.1 on 2026-07-31 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_assignment_grading_mode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignmentattachment',
            options={'ordering': ['assignment', 'order']},
        ),
        migrations.AddField(
            model_name='assignmentattachment',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
