# Generated by Django 5.1 on 2026-09-04 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='ai_review_reward_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='grading_mode',
            field=models.CharField(choices=[('MANUAL', 'Manual Review'), ('AUTO', 'Auto-Check on Submit'), ('AI', 'AI Review')], default='MANUAL', max_length=20),
        ),
        migrations.CreateModel(
            name='AssignmentRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('passing_threshold_percent', models.PositiveIntegerField(default=70)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rubric', to='assignments.assignment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssignmentRubricCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('weight', models.PositiveIntegerField(default=1)),
                ('order', models.PositiveIntegerField(default=0)),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='assignments.assignmentrubric')),
            ],
            options={
                'ordering': ['rubric', 'order'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentAIReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('result_status', models.CharField(blank=True, choices=[('PASS', 'Pass'), ('REVISION_REQUIRED', 'Revision Required')], max_length=20, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('criteria_results', models.JSONField(blank=True, default=list)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('improvements', models.JSONField(blank=True, default=list)),
                ('revision_guidance', models.TextField(blank=True)),
                ('computed_reward_points', models.PositiveIntegerField(default=0)),
                ('awarded_points', models.PositiveIntegerField(default=0)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_reviews', to='assignments.assignmentsubmission')),
            ],
            options={
                'ordering': ['submission', '-attempt_number'],
                'unique_together': {('submission', 'attempt_number')},
            },
        ),
    ]
