# Generated by Django 5.1 on 2026-09-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_assignment_ai_review_reward_points_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='ai_review_reward_points',
        ),
        migrations.RemoveField(
            model_name='assignmentaireview',
            name='awarded_points',
        ),
        migrations.RemoveField(
            model_name='assignmentaireview',
            name='computed_reward_points',
        ),
        migrations.RemoveField(
            model_name='assignmentrubriccriterion',
            name='weight',
        ),
        migrations.AddField(
            model_name='assignmentrubric',
            name='grading_method',
            field=models.CharField(choices=[('RUBRIC', 'Rubric / Criteria Based'), ('QUESTION_BASED', 'Question Based')], default='RUBRIC', max_length=20),
        ),
        migrations.AddField(
            model_name='assignmentrubriccriterion',
            name='max_marks',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
