# Generated by Django 5.1 on 2026-07-31 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_backfill_assignmentattachment_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='submission_text',
        ),
    ]
