# Generated by Django 5.1 on 2026-09-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_remove_assignmentaireview_result_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='grading_mode',
            field=models.CharField(choices=[('MANUAL', 'Manual Review'), ('AI', 'AI Grading')], default='MANUAL', max_length=20),
        ),
    ]
