# Generated by Django 5.1 on 2026-10-02 10:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_message_course_message_course_progress_percentage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='conversation',
            name='conversation_type',
            field=models.CharField(choices=[('DIRECT', 'Direct'), ('ADVISOR', 'Advisor')], default='DIRECT', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('participant_one', 'participant_two', 'conversation_type')},
        ),
    ]
