# Generated by Django 5.1 on 2026-08-18 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('future_clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='futureclientapplication',
            name='created_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='future_client_application', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='futureclientapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_future_client_applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
