# Generated by Django 5.1 on 2026-09-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userinvitation_invitationfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationfeedback',
            name='admin_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitationfeedback',
            name='admin_email_status',
            field=models.CharField(default='NOT_SENT', max_length=20),
        ),
    ]
