# Generated by Django 5.1 on 2026-10-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_invitationfeedback_admin_email_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_advisor',
            field=models.BooleanField(default=False),
        ),
    ]
