# Generated by Django 5.1 on 2026-08-18 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pathways', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pathwayenrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathway_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='pathwaycourse',
            constraint=models.UniqueConstraint(condition=models.Q(('pathway__isnull', False)), fields=('pathway', 'order'), name='unique_pathwaycourse_order_per_pathway'),
        ),
        migrations.AlterUniqueTogether(
            name='pathwaycourse',
            unique_together={('pathway', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='pathwayenrollment',
            unique_together={('user', 'pathway')},
        ),
    ]
