# Generated by Django 5.1 on 2026-08-19 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0002_initial'),
        ('tiers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathway',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pathway',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pathways', to='tiers.tier'),
        ),
        migrations.AddConstraint(
            model_name='pathway',
            constraint=models.UniqueConstraint(condition=models.Q(('tier__isnull', False)), fields=('tier', 'order'), name='unique_pathway_order_per_tier'),
        ),
    ]
