# Generated by Django 5.1 on 2026-08-19 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0003_pathway_order_pathway_tier_and_more'),
        ('tiers', '0003_backfill_tierpathway'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pathway',
            name='unique_pathway_order_per_tier',
        ),
        migrations.RemoveField(
            model_name='pathway',
            name='order',
        ),
        migrations.RemoveField(
            model_name='pathway',
            name='tier',
        ),
    ]
