# Generated by Django 5.1 on 2026-08-20 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0004_remove_pathway_unique_pathway_order_per_tier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathway',
            name='thumbnail',
        ),
    ]
