# Generated by Django 5.1 on 2026-10-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0005_remove_pathway_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathway',
            name='difficulty',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='BEGINNER', max_length=20),
        ),
        migrations.AddField(
            model_name='pathway',
            name='duration_weeks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pathway',
            name='learning_outcomes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='pathway',
            name='prerequisites',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='pathway',
            name='purpose',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pathway',
            name='who_is_for',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
