# Generated by Django 5.1 on 2026-10-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0006_pathway_difficulty_pathway_duration_weeks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='pathway',
            name='audiences',
            field=models.ManyToManyField(blank=True, related_name='pathways', to='pathways.audience'),
        ),
    ]
