# Generated by Django 5.1 on 2026-08-18 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('daily_drill', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='drillattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drill_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drillattempt',
            name='selected_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='daily_drill.drilloption'),
        ),
        migrations.AddField(
            model_name='drilloption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='daily_drill.drillquestion'),
        ),
        migrations.AddField(
            model_name='drillattempt',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='daily_drill.drillquestion'),
        ),
        migrations.AddConstraint(
            model_name='drilloption',
            constraint=models.UniqueConstraint(fields=('question', 'key'), name='unique_drill_option_key_per_question'),
        ),
        migrations.AddConstraint(
            model_name='drillattempt',
            constraint=models.UniqueConstraint(fields=('student', 'attempt_date'), name='one_drill_attempt_per_day'),
        ),
    ]
