# Generated by Django 5.1 on 2026-09-03 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_drill', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDrillQuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['schedule', 'order'],
            },
        ),
        migrations.CreateModel(
            name='AdminDrillQuizChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='daily_drill.admindrillquizquestion')),
            ],
            options={
                'ordering': ['question', 'order'],
            },
        ),
        migrations.CreateModel(
            name='AdminDrillSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='daily_drills/')),
                ('scheduled_date', models.DateField(unique=True)),
                ('reward_points', models.PositiveIntegerField()),
                ('passing_score_percent', models.PositiveSmallIntegerField(default=60)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.AddField(
            model_name='admindrillquizquestion',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='daily_drill.admindrillschedule'),
        ),
        migrations.CreateModel(
            name='AdminDrillProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=20)),
                ('video_progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('quiz_answers', models.JSONField(blank=True, null=True)),
                ('score_percent', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('attempts_count', models.PositiveIntegerField(default=0)),
                ('points_awarded', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_drill_progress', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='daily_drill.admindrillschedule')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'schedule'), name='one_progress_per_student_per_schedule')],
            },
        ),
        migrations.CreateModel(
            name='AIDrillGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drill_date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('question', models.TextField()),
                ('context', models.TextField(blank=True)),
                ('options', models.JSONField()),
                ('correct_answer', models.CharField(max_length=1)),
                ('explanation', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=20)),
                ('topic', models.CharField(blank=True, max_length=255)),
                ('content_fingerprint', models.CharField(blank=True, db_index=True, max_length=64)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('is_completed', models.BooleanField(default=False)),
                ('selected_key', models.CharField(blank=True, max_length=1)),
                ('points_awarded', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_drill_generations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-drill_date'],
                'constraints': [models.UniqueConstraint(fields=('student', 'drill_date'), name='one_ai_drill_per_student_per_day')],
            },
        ),
    ]
